import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import ReactQueryProvider from '@/app/_utils/ReactQueryProvider'
import 'bootstrap/dist/css/bootstrap.min.css'
import TopNav from '@/app/_component/layout/TopNav'
import React from 'react'
import Footer from '@/app/_component/layout/Footer'
import { Container, Row } from 'react-bootstrap'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased  vw-100 vh-100 `}>
        <ReactQueryProvider>
          <Container className={'d-flex flex-column m-0 vw-100 vh-100 p-0 '} fluid>
            <div>
              <TopNav />
            </div>
            <div className={'overflow-auto h-100'}>{children}</div>
            {/*<Footer />*/}
          </Container>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
